spring:
  config:
    import: application-mysql.yml, application-flask.yml
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
springdoc:
  swagger-ui:
    operations-sorter: method
