name: PR CI

on:
  push:
    paths:
      - '/**'
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start

      - name: Create Database
        run: |
          mysql -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE \`retrospect-project\`;"

      - name: Make Application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          touch ./application-flask.yml
          touch ./application.mysql.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
          echo "${{ secrets.FLASK }}" > ./application-flask.yml
          echo "${{ secrets.MYSQL }}" > ./application-mysql.yml

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: Cleanup Gradle Cache
        if: always()
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
